### ISSUE TITLE
Lucene-7 branch doesn't support Lucene 7.7

### ISSUE THREAD

**Issue by TheFlow0360** [flaxsearch/marple#62]
I tried to open an index created with the current lucene 7.7.1, but it fails with the following message:

    Exception in thread "main" org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\my-index-path\segments_f"))): 9 (needs to be between 6 and 7)
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:59)
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:56)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:670)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:79)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
        at com.github.flaxsearch.util.FSReaderManager.<init>(FSReaderManager.java:41)
        at com.github.flaxsearch.MarpleApplication.run(MarpleApplication.java:52)
        at com.github.flaxsearch.MarpleApplication.run(MarpleApplication.java:34)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at com.github.flaxsearch.MarpleApplication.main(MarpleApplication.java:68)

**Comment by teamstand-arun** [comment]
:+1:

**Comment by teamstand-arun** [comment]
Facing the same issue.

**Comment by epugh** [comment]
Hi, I'd love a Pull Request to review updating these.   We did just add missing codecs as well....

**Comment by Davidportlouis** [comment]
Hi, Is some one working on adding the missing codecs ?
